export const individualPolicyPlan = [
  { name: "Annuity plan" },
  { name: "Comprehensive Auto Insurance Plan" },
  { name: "Third Party Auto Insurance Plan" },
  { name: "Enhanced Third Party Auto Insurance Plan" },
  { name: "Flexible Endowment Plan" },
  { name: "Children Education Plan (CEP)" },
  { name: "Corporate Savings Investent Plan" },
  { name: "New Income Investment Plan" },
  { name: "Education Legacy Assurance Plan" },
  { name: "Credit Life Policy Plan" },
  { name: "Covid 19 Plan" },
  { name: "Personal Accident Plan" },
  { name: "Home Insurance Plan" },
  { name: "Travel Incurance Plan" },
  { name: "Mortgage Protection Assurance Plan" },
  { name: "Team Assurance Plan" },
  { name: "Money Wise Plan" },
  { name: "Life Celebration Plan" },
  { name: "Hospital Cash Plan" },
  { name: "Criticare Plan" },
];

export const companyPolicyPlan = [
  { name: "Marine Insurance (Cargo) Plan" },
  { name: "Service Hull & Machinery Insurance" },
  { name: "Machinery Loss of Profit (MLOP)" },
  { name: "Machinery Breakdown Insurance" },
  { name: "Oil and Gas Insurance Plan" },
  { name: "Agric Insurance Plan" },
  { name: "Group Life Insurance Plan" },
  { name: "Group Education Insurance Plan" },
  { name: "Fire & Special Peril Insurance Plan" },
  { name: "Consequential Loss Insurance Plan" },
  { name: "Contractor-All-Risk Insurance Plan" },
  { name: "Electronic Equipment Policy Insurance Plan" },
  { name: "Employer's Liability Insurance Plan" },
  { name: "Erection-All-Risk Insurance Plan" },
  { name: "Fidelity Guarantee Insurance Plan" },
  { name: "Goods-In-Transit Insurance Plan" },
  { name: "Fire Burgulary & Insurance Plan" },
];
